### ISSUE TITLE
Scenario 7.0 breaks with Python 3.8

### ISSUE THREAD

**Issue by tonyandrewmeyer** [canonical/ops-scenario#187]
```
tameyer@tam-canoncial-1:~/code/ops-scenario$ uvx --python=3.8 tox -e unit
[...]
________________________________________________________________ ERROR collecting tests/test_runtime.py ________________________________________________________________
Traceback (most recent call last):
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/runner.py", line 389, in collect
    return list(collector.collect())
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/python.py", line 549, in collect
    self._register_setup_module_fixture()
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/python.py", line 562, in _register_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/python.py", line 284, in obj
    self._obj = obj = self._getobj()
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/python.py", line 546, in _getobj
    return importtestmodule(self.path, self.config)
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/python.py", line 493, in importtestmodule
    mod = import_path(
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/pathlib.py", line 582, in import_path
    importlib.import_module(module_name)
  File "/home/tameyer/.local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/tameyer/code/ops-scenario/.tox/unit/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 174, in exec_module
    exec(co, module.__dict__)
  File "/home/tameyer/code/ops-scenario/tests/test_runtime.py", line 11, in <module>
    from scenario import Context
  File "/home/tameyer/code/ops-scenario/scenario/__init__.py", line 63, in <module>
    from scenario.context import Context, Manager
  File "/home/tameyer/code/ops-scenario/scenario/context.py", line 16, in <module>
    from scenario.runtime import Runtime
  File "/home/tameyer/code/ops-scenario/scenario/runtime.py", line 31, in <module>
    from scenario.state import (
  File "/home/tameyer/code/ops-scenario/scenario/state.py", line 1352, in <module>
    class State(_max_posargs(0)):
  File "/home/tameyer/code/ops-scenario/scenario/state.py", line 1388, in State
    model: Model = Model()
  File "/home/tameyer/code/ops-scenario/scenario/state.py", line 182, in __new__
    raise TypeError(f"{cls.__name__} missing required {details}") from None
TypeError: Model missing required positional: 'args' and keyword: 'kwargs' arguments
======================================================================= short test summary info ========================================================================
ERROR tests/test_charm_spec_autoload.py - TypeError: Model missing required positional: 'args' and keyword: 'kwargs' arguments
ERROR tests/test_consistency_checker.py - TypeError: Model missing required positional: 'args' and keyword: 'kwargs' [...]
arguments
ERROR tests/test_runtime.py - TypeError: Model missing required positional: 'args' and keyword: 'kwargs' arguments
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 26 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 26 errors in 0.59s ==========================================================================
unit: exit 2 (0.75 seconds) /home/tameyer/code/ops-scenario> pytest --cov-report html:.cov_html -v --tb native --log-cli-level=INFO -s /home/tameyer/code/ops-scenario/tests pid=1289054
  unit: FAIL code 2 (5.18=setup[4.43]+cmd[0.75] seconds)
  evaluation failed :( (5.21 seconds)
```

**Comment by tonyandrewmeyer** [comment]
Working on it, will have a PR up shortly.

**Comment by tonyandrewmeyer** [comment]
I was not aware of this Python change, and hadn't run with 3.8 for too long :disappointed:.

```
tameyer@tam-canoncial-1:~/code/ops-scenario$ cat /tmp/inspectchange.py 
class P:
    def __new__(cls, *args, **kwargs):
        return super.__new__(*args, **kwargs)

class A(P):
    def __init__(self, a, b=1):
        pass

import inspect
print(inspect.signature(A))

tameyer@tam-canoncial-1:~/code/ops-scenario$ pyenv shell 3.8; python /tmp/inspectchange.py 
(*args, **kwargs)
tameyer@tam-canoncial-1:~/code/ops-scenario$ pyenv shell 3.9; python /tmp/inspectchange.py 
(a, b=1)
```
