### ISSUE TITLE
KeyError when using model.get_relation when relation does not exist

### ISSUE THREAD

**Issue by gruyaume** [canonical/ops-scenario#193]
## Description

Get_relation raises a KeyError when the relation does not exist instead of returning None. 

## Current Behavior
- **Given** the relation does not exist
- **When** the charm calls `model.get_relation`
- **Then** get_relation raises a KeyError.

## Expected Behavior

- **Given** the relation does not exist
- **When** the charm calls `model.get_relation`
- **Then** get_relation returns None

## Scenario Test

```pytest
    def test_given_unrelated_relation_when_add_certificates_then_error_is_logged(
        self, caplog: pytest.LogCaptureFixture
    ):
        relation = scenario.Relation(
            endpoint="certificate_transfer", interface="certificate_transfer"
        )
        state_in = scenario.State(leader=True, relations=[relation])

        self.ctx.run(
            self.ctx.on.action(
                "add-certificates",
                params={
                    "certificates": "certificate",
                    "relation-id": str(relation.id + 1),  # non-existent relation id
                },
            ),
            state_in,
        )

        logs = [(record.levelname, record.module, record.message) for record in caplog.records]
        assert (
            "ERROR",
            "certificate_transfer",
            "At least 1 matching relation ID not found with the relation name 'certificate_transfer'",  # noqa: E501
        ) in logs
```

## Logs
```
Traceback (most recent call last):
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/runtime.py", line 467, in exec
    yield ops
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/context.py", line 664, in _run
    yield ops
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/context.py", line 641, in run
    ops.emit()
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/ops_main_mock.py", line 252, in emit
    _emit_charm_event(charm, dispatcher.event_name, self.event)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/ops_main_mock.py", line 100, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/runtime.py", line 538, in _wrapped_emit
    return _real_emit(self, evt)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/home/guillaume/code/certificate-transfer-interface/tests/unit/charms/certificate_transfer_interface/v1/test_certificate_transfer_provides_v1.py", line 29, in _on_add_certificates_action
    self.certificate_transfer.add_certificates(
  File "/home/guillaume/code/certificate-transfer-interface/lib/charms/certificate_transfer_interface/v1/certificate_transfer.py", line 234, in add_certificates
    relations = self._get_relevant_relations(relation_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/lib/charms/certificate_transfer_interface/v1/certificate_transfer.py", line 282, in _get_relevant_relations
    relation = self.model.get_relation(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/ops/model.py", line 250, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/ops/model.py", line 931, in _get_unique
    return Relation(
           ^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/ops/model.py", line 1623, in __init__
    for unit_name in backend.relation_list(self.id):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/mocking.py", line 275, in relation_list
    relation = self._get_relation_by_id(relation_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/mocking.py", line 183, in _get_relation_by_id
    return self._state.get_relation(rel_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/state.py", line 1566, in get_relation
    raise KeyError(f"relation: id={relation} not found in the State")
KeyError: 'relation: id=2 not found in the State'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
                             ^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
    yield
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
    yield
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/logging.py", line 846, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/logging.py", line 829, in _runtest_for
    yield
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/capture.py", line 880, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/skipping.py", line 257, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/_pytest/python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guillaume/code/certificate-transfer-interface/tests/unit/charms/certificate_transfer_interface/v1/test_certificate_transfer_provides_v1.py", line 92, in test_given_unrelated_relation_when_add_certificates_then_error_is_logged
    self.ctx.run(
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/context.py", line 640, in run
    with self._run(event=event, state=state) as ops:
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/context.py", line 659, in _run
    with runtime.exec(
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/guillaume/code/certificate-transfer-interface/.tox/unit/lib/python3.12/site-packages/scenario/runtime.py", line 475, in exec
    raise UncaughtCharmError(
scenario.errors.UncaughtCharmError: Uncaught exception (<class 'KeyError'>) in operator/charm code: KeyError('relation: id=2 not found in the State')
```

## Environment

- Scenario: 7.0.2
- Ops: 2.16.1

**Comment by tonyandrewmeyer** [comment]
> ## Expected Behavior
> * **Given** the relation does not exist
> * **When** the charm calls `model.get_relation`
> * **Then** get_relation returns None

The `KeyError` is wrong, but the expected behaviour is that `get_relation` returns an `ops.Relation` object with the specified ID (presumably a dead relation). For example, this charm:

```python
class AskForBadRelationIdCharm(ops.CharmBase):
    def __init__(self, framework: ops.Framework):
        super().__init__(framework)
        framework.observe(self.on.config_changed, self._on_config_changed)

    def _on_config_changed(self, event):
        logger.info("get: %r", self.model.get_relation("friend"))
        logger.info("get: %r", self.model.get_relation("friend", 1979))
```

Will give this debug-log output (the `21` will change):

```
unit-ask-for-bad-relation-id-0: 14:32:35 INFO unit.ask-for-bad-relation-id/0.juju-log get: <ops.model.Relation friend:21>
unit-ask-for-bad-relation-id-0: 14:32:35 INFO unit.ask-for-bad-relation-id/0.juju-log get: <ops.model.Relation friend:1979>
```

If you call `get_relation` with a relation name (endpoint) that isn't defined, then you'll get `None`, but if the relation is defined and you pass an ID that doesn't belong to a current relation, the assumption is that it used to exist (where else did you get the ID from?) and it's been removed, so [you get a dead relation](https://github.com/canonical/operator/blob/fdb2338d2cec5caed8b0445f824c3dfa55dab2dc/ops/model.py#L930).

I double-checked that we didn't recently change the behaviour here - it's the same at least as far back as ops 2.6.
