### ISSUE TITLE
 command not found: opened-ports

### ISSUE THREAD

**Issue by sed-i** [canonical/ops-scenario#49]
https://github.com/canonical/operator/pull/905 introduced new commands that scenario does not yet support.

```
Traceback (most recent call last):
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/scenario/runtime.py", line 387, in exec
    mocked_main(
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/scenario/ops_main_mock.py", line 132, in main
    charm = charm_class(framework)
  File "/home/code/o11y/alertmanager-k8s-operator/src/charm.py", line 131, in __init__
    self.set_ports()
  File "/home/code/o11y/alertmanager-k8s-operator/src/charm.py", line 232, in set_ports
    actual_ports = self.unit.opened_ports()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/ops/model.py", line 630, in opened_ports
    return self._backend.opened_ports()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/ops/model.py", line 3154, in opened_ports
    output = typing.cast(str, self._run('opened-ports', return_output=True))
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/ops/model.py", line 2686, in _run
    raise RuntimeError(f'command not found: {args[0]}')
RuntimeError: command not found: opened-ports

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 157, in pytest_runtest_setup
    item.session._setupstate.setup(item)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 497, in setup
    raise exc
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 494, in setup
    col.setup()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/python.py", line 1791, in setup
    self._request._fillfixtures()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 566, in _fillfixtures
    item.funcargs[argname] = self.getfixturevalue(argname)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 585, in getfixturevalue
    fixturedef = self._get_active_fixturedef(argname)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 607, in _get_active_fixturedef
    self._compute_fixture_value(fixturedef)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 693, in _compute_fixture_value
    fixturedef.execute(request=subrequest)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 1069, in execute
    result = ihook.pytest_fixture_setup(fixturedef=self, request=request)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 155, in _multicall
    return outcome.get_result()
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 1123, in pytest_fixture_setup
    result = call_fixture_func(fixturefunc, request, kwargs)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/fixtures.py", line 895, in call_fixture_func
    fixture_result = next(generator)
  File "/home/code/o11y/alertmanager-k8s-operator/tests/scenario/test_server_scheme.py", line 35, in initial_state
    state = begin_with_initial_hooks_isolated(context, leader=leader)
  File "/home/code/o11y/alertmanager-k8s-operator/tests/scenario/helpers.py", line 12, in begin_with_initial_hooks_isolated
    state = context.run("install", state)
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/scenario/context.py", line 151, in run
    return self._run(
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/scenario/context.py", line 221, in _run
    return runtime.exec(
  File "/home/code/o11y/alertmanager-k8s-operator/.tox/scenario/lib/python3.10/site-packages/scenario/runtime.py", line 400, in exec
    raise UncaughtCharmError(
scenario.runtime.UncaughtCharmError: Uncaught exception (<class 'RuntimeError'>) in operator/charm code: RuntimeError('command not found: opened-ports')
```

**Comment by PietroPasotti** [comment]
working on it
