### ISSUE TITLE
Regression between v5.4 and v5.8: `ValueError: invalid metadata: mandatory "name" field is missing`

### ISSUE THREAD

**Issue by sed-i** [canonical/ops-scenario#92]
cos-proxy stests [fail](https://github.com/canonical/cos-proxy-operator/actions/runs/7454173621/job/20281006341?pr=108) with:
```
Traceback (most recent call last):
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/him/code/o11y/cos-proxy-operator/tests/scenario/test_alerts.py", line 33, in test_relation
    state_out = ctx.run(monitors.changed_event, state_in)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/scenario/context.py", line 446, in run
    with self._run_event(event=event, state=state) as ops:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/scenario/context.py", line 419, in _run_event
    with self._run(event=_event, state=state) as ops:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/scenario/context.py", line 524, in _run
    runtime = Runtime(
  File "/home/him/code/o11y/cos-proxy-operator/.tox/scenario/lib/python3.10/site-packages/scenario/runtime.py", line 178, in __init__
    raise ValueError('invalid metadata: mandatory "name" field is missing.')
ValueError: invalid metadata: mandatory "name" field is missing.
```

**Comment by PietroPasotti** [comment]
Hum, same issue as @IbraAoad found yesterday. On it
